### PR TITLE
fix pip install issue

### PR DESCRIPTION
**Pull request by ltalirz**
change pip install instructions to include workaround for
[pip issue 5317](https://github.com/pypa/pip/issues/5317)

### CODE REVIEW

**Comment by ltalirz** [comment]
@jw1294 @MikeEntwistle 
I've now uploaded idea-public on TestPYPI. In order to install iDEA, please do: 
```
pip install --user --index-url https://test.pypi.org/simple/ idea-code
```

I've tested it on Ubuntu 16.04 and it worked for me - please test it as well.
Once we are happy, let me know. I will then upload it on the production PYPI and we can merge this pull request (which already contains the PYPI installation instructions)

**Comment by ltalirz** [comment]
P.S. In case you still want to wait with the PYPI release, that's fine as well.
An intermediate solution would be to make a "pre-release" with a version number `0.1.0a`, which pip recognizes and does not install, unless specifically asked to do so. 
I.e. `pip install idea-code` would not yet find anything, but `pip install --pre idea-code` would.  
This would allow us to already register the `idea-code` name.

**Comment by ltalirz** [comment]
Ok. I'll add the `--pre` flag to the installation instructions (to be removed after the full release).
Also, @jw1294 @MikeEntwistle could you please test the pip install
`pip install --user --index-url https://test.pypi.org/simple/ idea-code` drop me a line here on whether it works?

**Comment by jw1294** [comment]
This worked for me:
```
┌jw1294@research2:~
└pip install --user --index-url https://test.pypi.org/simple/ idea-code
Collecting idea-code
  Downloading https://test-files.pythonhosted.org/packages/92/68/18ebfee567baef6f79e66647882fb3107e4337d02bd572b58b5c0733b0c9/idea-code-0.1.1.tar.gz (598kB)
    100% |################################| 604kB 996kB/s 
Requirement already satisfied: matplotlib>=1.4 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from idea-code)
Requirement already satisfied: numpy>=1.10 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from idea-code)
Requirement already satisfied: scipy>=0.17 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from idea-code)
Requirement already satisfied: cython>=0.22 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from idea-code)
Requirement already satisfied: six>=1.10 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->idea-code)
Requirement already satisfied: python-dateutil in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->idea-code)
Requirement already satisfied: pytz in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->idea-code)
Requirement already satisfied: cycler>=0.10 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->idea-code)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /opt/yarcc/compilers/Anaconda3/4.3.1/1/default/anaconda3/lib/python3.6/site-packages (from matplotlib>=1.4->idea-code)
Building wheels for collected packages: idea-code
  Running setup.py bdist_wheel for idea-code ... done
  Stored in directory: /run/user/59099/cache/pip/wheels/fc/c4/70/b97c9e3bd41594245d13bfc90993e52d65a542149e333b3340
Successfully built idea-code
Installing collected packages: idea-code
Successfully installed idea-code-0.1.1
```

**Comment by jw1294** [comment]
@ltalirz If users install iDEA this way where does the directory that contains iDEA, outputs,example , parameters.py ect get created?

**Comment by ltalirz** [comment]
It will be in the site-packages folder, where all other python packages of your system are installed as well.

I mentioned some time ago that iDEA's structure currently does not follow regular python package conventions, and this is something we should change, when listing it on PYPI.

I'm going to add these modifications in a new PR #11 (closing this one for the moment so that it doesn't get merged inadvertedly)

**Pull request closed without merging**
